version: '3'
services:
  app:
    build: .
    pull_policy: build
    container_name: nintendo-museum-checker
    ports:
      - 3001:3001
    environment:
      - PORT=3000
    volumes:
      - ./data:/home/pptruser/screenshots # Montaje de vol√∫menes para persistir datos si es necesario
    restart: unless-stopped
